version: "3.9"

services:
  app:
    container_name: ${APP_HOSTNAME:-app}
    hostname: ${APP_HOSTNAME:-app}
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${APP_OUTER_PORT:-8000}:${APP_INNER_PORT:-8000}
    command: >
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port ${APP_INNER_PORT:-8000}